[package]
name = "mdbook-yapp"
version = "1.1.0"
authors = ["Dariusz Depta <depta@engos.de>"]
description = "A mdBook preprocessor for simple text replacements"
documentation = "https://docs.rs/mdbook-yapp"
repository = "https://github.com/EngosSoftware/yapp.git"
keywords = ["mdbook", "preprocessor", "replace", "text", "pattern"]
categories = ["template-engine", "text-processing"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
mdbook = "0.4.37"
semver = "1.0.22"
serde_json = "1.0.116"
